
GET http://localhost:3000/subscribers

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Cihat",
  "subscribedChannel": "Cihat Channel"
}

###

GET  http://localhost:3000/subscribers/6126acca46f4d19a43a7cdc7

###

DELETE  http://localhost:3000/subscribers/6126afbcfda1d4c2a1a29813

###

PATCH http://localhost:3000/subscribers/6126afbdfda1d4c2a1a29815
Content-Type: application/json 

{
  "name": "Mahmut",
  "subscribedChannel": "Mahmut'un Kanalı"
}